apiVersion: v1
kind: App
metadata:
  name: sacolaum
spec:
  # Environment variables
  env:
    - name: NODE_ENV
      value: production
    - name: PORT
      value: '8080'
    - name: DATABASE_URL
      # IMPORTANT: Set this in Koyeb's environment variables UI
      # Format: postgresql://username:password@host:port/database
      # Do NOT commit actual database credentials to this file

  # Services
  services:
    - name: web
      source:
        git:
          repository: https://github.com/marcythany/sacolaum
          branch: main
      build:
        docker:
          dockerfile: Dockerfile
      ports:
        - port: 8080
          public: true
          protocol: http
      health_checks:
        - type: http
          port: 8080
          path: /api/products
          initial_delay: 10
          interval: 30
          timeout: 5
          retries: 3
      # Instance configuration
      instance:
        type: nano
      # Scaling
      scaling:
        min: 1
        max: 3

  # Domains (optional - will be auto-generated if not specified)
  # domains:
  #   - name: your-app.koyeb.app
