services:
  - type: web
    name: sacolaum-prod
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: MONGO_URI
      - key: NODE_ENV
        value: production
    branch: main
